import { Pokemon } from "./Interfaces/Pokemon";


const AllPokemon: Pokemon[] = [
    {
        id: 1,
        name: "Bulbasaur",
        image: "./assets/assets/pokemons/default/alpha.jpg",
        type: ["Grass", "Poison"],
        height: 0.7,
        weight: 6.9,
        baseExperience: 64,
    },
    {
        id: 2,
        name: "Ivysaur",
        image: "/assets/assets/pokemons/default/2.png",
        type: ["Grass", "Poison"],
        height: 1,
        weight: 13,
        baseExperience: 142,
    },
    {
        id: 3,
        name: "Venusaur",
        image: "/assets/assets/pokemons/default/3.png",
        type: ["Grass", "Poison"],
        height: 2,
        weight: 100,
        baseExperience: 236,
    },
    {
        id: 4,
        name: "Charmander",
        image: "/assets/assets/pokemons/default/4.png",
        type: ["Fire"],
        height: 0.6,
        weight: 8.5,
        baseExperience: 62,
    },
    {
        id: 5,
        name: "Charmeleon",
        image: "/assets/assets/pokemons/default/5.png",
        type: ["Fire"],
        height: 1.1,
        weight: 19,
        baseExperience: 142,
    },
    {
        id: 6,
        name: "Charizard",
        image: "/assets/assets/pokemons/default/6.png",
        type: ["Fire", "Flying"],
        height: 1.7,
        weight: 90.5,
        baseExperience: 240,
    },
    {
        id: 7,
        name: "Squirtle",
        image: "/assets/assets/pokemons/default/7.png",
        type: ["Water"],
        height: 0.5,
        weight: 9,
        baseExperience: 63,
    },
    {
        id: 8,
        name: "Wartortle",
        image: "/assets/assets/pokemons/default/8.png",
        type: ["Water"],
        height: 1,
        weight: 22.5,
        baseExperience: 142,
    },
    {
        id: 9,
        name: "Blastoise",
        image: "/assets/assets/pokemons/default/9.png",
        type: ["Water"],
        height: 1.6,
        weight: 85.5,
        baseExperience: 239,
    },
    {
        id: 10,
        name: "Caterpie",
        image: "/assets/assets/pokemons/default/10.png",
        type: ["Bug"],
        height: 0.3,
        weight: 2.9,
        baseExperience: 39,
    },
    {
        id: 11,
        name: "Metapod",
        image: "/assets/assets/pokemons/default/11.png",
        type: ["Bug"],
        height: 0.7,
        weight: 9.9,
        baseExperience: 72,
    },
    {
        id: 12,
        name: "Butterfree",
        image: "/assets/assets/pokemons/default/12.png",
        type: ["Bug", "Flying"],
        height: 1.1,
        weight: 32,
        baseExperience: 178,
    },
    {
        id: 13,
        name: "Weedle",
        image: "/assets/assets/pokemons/default/13.png",
        type: ["Bug", "Poison"],
        height: 0.3,
        weight: 3.2,
        baseExperience: 39,
    },
    {
        id: 14,
        name: "Kakuna",
        image: "/assets/assets/pokemons/default/14.png",
        type: ["Bug", "Poison"],
        height: 0.6,
        weight: 10,
        baseExperience: 72,
    },
    {
        id: 15,
        name: "Beedrill",
        image: "/assets/assets/pokemons/default/15.png",
        type: ["Bug", "Poison"],
        height: 1,
        weight: 29.5,
        baseExperience: 178,
    },
    {
        id: 16,
        name: "Pidgey",
        image: "/assets/assets/pokemons/default/16.png",
        type: ["Normal", "Flying"],
        height: 0.3,
        weight: 1.8,
        baseExperience: 50,
    },
    {
        id: 17,
        name: "Pidgeotto",
        image: "/assets/assets/pokemons/default/17.png",
        type: ["Normal", "Flying"],
        height: 1.1,
        weight: 30,
        baseExperience: 122,
    },
    {
        id: 18,
        name: "Pidgeot",
        image: "/assets/assets/pokemons/default/18.png",
        type: ["Normal", "Flying"],
        height: 1.5,
        weight: 39.5,
        baseExperience: 216,
    },
    {
        id: 19,
        name: "Rattata",
        image: "/assets/assets/pokemons/default/19.png",
        type: ["Normal"],
        height: 0.3,
        weight: 3.5,
        baseExperience: 51,
    },
    {
        id: 20,
        name: "Raticate",
        image: "/assets/assets/pokemons/default/20.png",
        type: ["Normal"],
        height: 0.7,
        weight: 18.5,
        baseExperience: 145,
    },
    {
        id: 21,
        name: "Spearow",
        image: "/assets/assets/pokemons/default/21.png",
        type: ["Normal", "Flying"],
        height: 0.3,
        weight: 2,
        baseExperience: 52,
    },
    {
        id: 22,
        name: "Fearow",
        image: "/assets/assets/pokemons/default/22.png",
        type: ["Normal", "Flying"],
        height: 1.2,
        weight: 38,
        baseExperience: 155,
    },
    {
        id: 23,
        name: "Ekans",
        image: "/assets/assets/pokemons/default/23.png",
        type: ["Poison"],
        height: 2,
        weight: 6.9,
        baseExperience: 58,
    },
    {
        id: 24,
        name: "Arbok",
        image: "/assets/assets/pokemons/default/24.png",
        type: ["Poison"],
        height: 3.5,
        weight: 65,
        baseExperience: 157,
    },
    {
        id: 25,
        name: "Pikachu",
        image: "/assets/assets/pokemons/default/25.png",
        type: ["Electric"],
        height: 0.4,
        weight: 6,
        baseExperience: 112,
    },
    {
        id: 26,
        name: "Raichu",
        image: "/assets/assets/pokemons/default/26.png",
        type: ["Electric"],
        height: 0.8,
        weight: 30,
        baseExperience: 218,
    },
    {
        id: 27,
        name: "Sandshrew",
        image: "/assets/assets/pokemons/default/27.png",
        type: ["Ground"],
        height: 0.6,
        weight: 12,
        baseExperience: 60,
    },
    {
        id: 28,
        name: "Sandslash",
        image: "/assets/assets/pokemons/default/28.png",
        type: ["Ground"],
        height: 1,
        weight: 29.5,
        baseExperience: 158,
    },
    {
        id: 29,
        name: "Nidoran♀",
        image: "/assets/assets/pokemons/default/29.png",
        type: ["Poison"],
        height: 0.4,
        weight: 7,
        baseExperience: 55,
    },
    {
        id: 30,
        name: "Nidorina",
        image: "/assets/assets/pokemons/default/30.png",
        type: ["Poison"],
        height: 0.8,
        weight: 20,
        baseExperience: 128,
    },
    {
        id: 31,
        name: "Nidoqueen",
        image: "/assets/assets/pokemons/default/31.png",
        type: ["Poison", "Ground"],
        height: 1.3,
        weight: 60,
        baseExperience: 227,
    },
    {
        id: 32,
        name: "Nidoran♂",
        image: "/assets/assets/pokemons/default/32.png",
        type: ["Poison"],
        height: 0.5,
        weight: 9,
        baseExperience: 55,
    },
    {
        id: 33,
        name: "Nidorino",
        image: "/assets/assets/pokemons/default/33.png",
        type: ["Poison"],
        height: 0.9,
        weight: 19.5,
        baseExperience: 128,
    },
    {
        id: 34,
        name: "Nidoking",
        image: "/assets/assets/pokemons/default/34.png",
        type: ["Poison", "Ground"],
        height: 1.4,
        weight: 62,
        baseExperience: 223,
    },
    {
        id: 35,
        name: "Clefairy",
        image: "/assets/assets/pokemons/default/35.png",
        type: ["Fairy"],
        height: 0.6,
        weight: 7.5,
        baseExperience: 113,
    },
    {
        id: 36,
        name: "Clefable",
        image: "/assets/assets/pokemons/default/36.png",
        type: ["Fairy"],
        height: 1.3,
        weight: 40,
        baseExperience: 217,
    },
    {
        id: 37,
        name: "Vulpix",
        image: "/assets/assets/pokemons/default/37.png",
        type: ["Fire"],
        height: 0.6,
        weight: 9.9,
        baseExperience: 60,
    },
    {
        id: 38,
        name: "Ninetales",
        image: "/assets/assets/pokemons/default/38.png",
        type: ["Fire"],
        height: 1.1,
        weight: 19.9,
        baseExperience: 177,
    },
    {
        id: 39,
        name: "Jigglypuff",
        image: "/assets/assets/pokemons/default/39.png",
        type: ["Normal", "Fairy"],
        height: 0.5,
        weight: 5.5,
        baseExperience: 95,
    },
    {
        id: 40,
        name: "Wigglytuff",
        image: "/assets/assets/pokemons/default/40.png",
        type: ["Normal", "Fairy"],
        height: 1,
        weight: 12,
        baseExperience: 196,
    },
    {
        id: 41,
        name: "Zubat",
        image: "/assets/assets/pokemons/default/41.png",
        type: ["Poison", "Flying"],
        height: 0.8,
        weight: 7.5,
        baseExperience: 49,
    },
    {
        id: 42,
        name: "Golbat",
        image: "/assets/assets/pokemons/default/42.png",
        type: ["Poison", "Flying"],
        height: 1.6,
        weight: 55,
        baseExperience: 159,
    },
    {
        id: 43,
        name: "Oddish",
        image: "/assets/assets/pokemons/default/43.png",
        type: ["Grass", "Poison"],
        height: 0.5,
        weight: 5.4,
        baseExperience: 64,
    },
    {
        id: 44,
        name: "Gloom",
        image: "/assets/assets/pokemons/default/44.png",
        type: ["Grass", "Poison"],
        height: 0.8,
        weight: 8.6,
        baseExperience: 138,
    },
    {
        id: 45,
        name: "Vileplume",
        image: "/assets/assets/pokemons/default/45.png",
        type: ["Grass", "Poison"],
        height: 1.2,
        weight: 18.6,
        baseExperience: 221,
    },
    {
        id: 46,
        name: "Paras",
        image: "/assets/assets/pokemons/default/46.png",
        type: ["Bug", "Grass"],
        height: 0.3,
        weight: 5.4,
        baseExperience: 57,
    },
    {
        id: 47,
        name: "Parasect",
        image: "/assets/assets/pokemons/default/47.png",
        type: ["Bug", "Grass"],
        height: 1,
        weight: 29.5,
        baseExperience: 142,
    },
    {
        id: 48,
        name: "Venonat",
        image: "/assets/assets/pokemons/default/48.png",
        type: ["Bug", "Poison"],
        height: 1,
        weight: 30,
        baseExperience: 61,
    },
    {
        id: 49,
        name: "Venomoth",
        image: "/assets/assets/pokemons/default/49.png",
        type: ["Bug", "Poison"],
        height: 1.5,
        weight: 12.5,
        baseExperience: 158,
    },
    {
        id: 50,
        name: "Diglett",
        image: "/assets/assets/pokemons/default/50.png",
        type: ["Ground"],
        height: 0.2,
        weight: 0.8,
        baseExperience: 53,
    }, {
        id: 51,
        name: "Dugtrio",
        image: "/assets/assets/pokemons/default/51.png",
        type: ["Ground"],
        height: 0.7,
        weight: 33.3,
        baseExperience: 149,
    },
    {
        id: 52,
        name: "Meowth",
        image: "/assets/assets/pokemons/default/52.png",
        type: ["Normal"],
        height: 0.4,
        weight: 4.2,
        baseExperience: 58,
    },
    {
        id: 53,
        name: "Persian",
        image: "/assets/assets/pokemons/default/53.png",
        type: ["Normal"],
        height: 1,
        weight: 32,
        baseExperience: 154,
    },
    {
        id: 54,
        name: "Psyduck",
        image: "/assets/assets/pokemons/default/54.png",
        type: ["Water"],
        height: 0.8,
        weight: 19.6,
        baseExperience: 64,
    },
    {
        id: 55,
        name: "Golduck",
        image: "/assets/assets/pokemons/default/55.png",
        type: ["Water"],
        height: 1.7,
        weight: 76.6,
        baseExperience: 175,
    },
    {
        id: 56,
        name: "Mankey",
        image: "/assets/assets/pokemons/default/56.png",
        type: ["Fighting"],
        height: 0.5,
        weight: 28,
        baseExperience: 61,
    },
    {
        id: 57,
        name: "Primeape",
        image: "/assets/assets/pokemons/default/57.png",
        type: ["Fighting"],
        height: 1,
        weight: 32,
        baseExperience: 159,
    },
    {
        id: 58,
        name: "Growlithe",
        image: "/assets/assets/pokemons/default/58.png",
        type: ["Fire"],
        height: 0.7,
        weight: 19,
        baseExperience: 70,
    },
    {
        id: 59,
        name: "Arcanine",
        image: "/assets/assets/pokemons/default/59.png",
        type: ["Fire"],
        height: 1.9,
        weight: 155,
        baseExperience: 194,
    },
    {
        id: 60,
        name: "Poliwag",
        image: "/assets/assets/pokemons/default/60.png",
        type: ["Water"],
        height: 0.6,
        weight: 12.4,
        baseExperience: 60,
    },
    {
        id: 61,
        name: "Poliwhirl",
        image: "/assets/assets/pokemons/default/61.png",
        type: ["Water"],
        height: 1,
        weight: 20,
        baseExperience: 135,
    },
    {
        id: 62,
        name: "Poliwrath",
        image: "/assets/assets/pokemons/default/62.png",
        type: ["Water", "Fighting"],
        height: 1.3,
        weight: 54,
        baseExperience: 230,
    },
    {
        id: 63,
        name: "Abra",
        image: "/assets/assets/pokemons/default/63.png",
        type: ["Psychic"],
        height: 0.9,
        weight: 19.5,
        baseExperience: 62,
    },
    {
        id: 64,
        name: "Kadabra",
        image: "/assets/assets/pokemons/default/64.png",
        type: ["Psychic"],
        height: 1.3,
        weight: 56.5,
        baseExperience: 140,
    },
    {
        id: 65,
        name: "Alakazam",
        image: "/assets/assets/pokemons/default/65.png",
        type: ["Psychic"],
        height: 1.5,
        weight: 48,
        baseExperience: 225,
    },
    {
        id: 66,
        name: "Machop",
        image: "/assets/assets/pokemons/default/66.png",
        type: ["Fighting"],
        height: 0.8,
        weight: 19.5,
        baseExperience: 61,
    },
    {
        id: 67,
        name: "Machoke",
        image: "/assets/assets/pokemons/default/67.png",
        type: ["Fighting"],
        height: 1.5,
        weight: 70.5,
        baseExperience: 142,
    },
    {
        id: 68,
        name: "Machamp",
        image: "/assets/assets/pokemons/default/68.png",
        type: ["Fighting"],
        height: 1.6,
        weight: 130,
        baseExperience: 227,
    },
    {
        id: 69,
        name: "Bellsprout",
        image: "/assets/assets/pokemons/default/69.png",
        type: ["Grass", "Poison"],
        height: 0.7,
        weight: 4,
        baseExperience: 60,
    },
    {
        id: 70,
        name: "Weepinbell",
        image: "/assets/assets/pokemons/default/70.png",
        type: ["Grass", "Poison"],
        height: 1,
        weight: 6.4,
        baseExperience: 137,
    },
    {
        id: 71,
        name: "Victreebel",
        image: "/assets/assets/pokemons/default/71.png",
        type: ["Grass", "Poison"],
        height: 1.7,
        weight: 15.5,
        baseExperience: 221,
    },
    {
        id: 72,
        name: "Tentacool",
        image: "/assets/assets/pokemons/default/72.png",
        type: ["Water", "Poison"],
        height: 0.9,
        weight: 45.5,
        baseExperience: 67,
    },
    {
        id: 73,
        name: "Tentacruel",
        image: "/assets/assets/pokemons/default/73.png",
        type: ["Water", "Poison"],
        height: 1.6,
        weight: 55,
        baseExperience: 180,
    },
    {
        id: 74,
        name: "Geodude",
        image: "/assets/assets/pokemons/default/74.png",
        type: ["Rock", "Ground"],
        height: 0.4,
        weight: 20,
        baseExperience: 60,
    },
    {
        id: 75,
        name: "Graveler",
        image: "/assets/assets/pokemons/default/75.png",
        type: ["Rock", "Ground"],
        height: 1,
        weight: 105,
        baseExperience: 137,
    },
    {
        id: 76,
        name: "Golem",
        image: "/assets/assets/pokemons/default/76.png",
        type: ["Rock", "Ground"],
        height: 1.4,
        weight: 300,
        baseExperience: 218,
    },
    {
        id: 77,
        name: "Ponyta",
        image: "/assets/assets/pokemons/default/77.png",
        type: ["Fire"],
        height: 1,
        weight: 30,
        baseExperience: 82,
    },
    {
        id: 78,
        name: "Rapidash",
        image: "/assets/assets/pokemons/default/78.png",
        type: ["Fire"],
        height: 1.7,
        weight: 95,
        baseExperience: 175,
    },
    {
        id: 79,
        name: "Slowpoke",
        image: "/assets/assets/pokemons/default/79.png",
        type: ["Water", "Psychic"],
        height: 1.2,
        weight: 36,
        baseExperience: 63,
    },
    {
        id: 80,
        name: "Slowbro",
        image: "/assets/assets/pokemons/default/80.png",
        type: ["Water", "Psychic"],
        height: 1.6,
        weight: 78.5,
        baseExperience: 172,
    },
    {
        id: 81,
        name: "Magnemite",
        image: "/assets/assets/pokemons/default/81.png",
        type: ["Electric", "Steel"],
        height: 0.3,
        weight: 6,
        baseExperience: 65,
    },
    {
        id: 82,
        name: "Magneton",
        image: "/assets/assets/pokemons/default/82.png",
        type: ["Electric", "Steel"],
        height: 1,
        weight: 60,
        baseExperience: 163,
    },
    {
        id: 83,
        name: "Farfetch'd",
        image: "/assets/assets/pokemons/default/83.png",
        type: ["Normal", "Flying"],
        height: 0.8,
        weight: 15,
        baseExperience: 123,
    },
    {
        id: 84,
        name: "Doduo",
        image: "/assets/assets/pokemons/default/84.png",
        type: ["Normal", "Flying"],
        height: 1.4,
        weight: 39.2,
        baseExperience: 62,
    },
    {
        id: 85,
        name: "Dodrio",
        image: "/assets/assets/pokemons/default/85.png",
        type: ["Normal", "Flying"],
        height: 1.8,
        weight: 85.2,
        baseExperience: 165,
    },
    {
        id: 86,
        name: "Seel",
        image: "/assets/assets/pokemons/default/86.png",
        type: ["Water"],
        height: 1.1,
        weight: 90,
        baseExperience: 65,
    },
    {
        id: 87,
        name: "Dewgong",
        image: "/assets/assets/pokemons/default/87.png",
        type: ["Water", "Ice"],
        height: 1.7,
        weight: 120,
        baseExperience: 166,
    },
    {
        id: 88,
        name: "Grimer",
        image: "/assets/assets/pokemons/default/88.png",
        type: ["Poison"],
        height: 0.9,
        weight: 30,
        baseExperience: 65,
    },
    {
        id: 89,
        name: "Muk",
        image: "/assets/assets/pokemons/default/89.png",
        type: ["Poison"],
        height: 1.2,
        weight: 30,
        baseExperience: 175,
    },
    {
        id: 90,
        name: "Shellder",
        image: "/assets/assets/pokemons/default/90.png",
        type: ["Water"],
        height: 0.3,
        weight: 4,
        baseExperience: 61,
    },
    {
        id: 91,
        name: "Cloyster",
        image: "/assets/assets/pokemons/default/91.png",
        type: ["Water", "Ice"],
        height: 1.5,
        weight: 132.5,
        baseExperience: 184,
    },
    {
        id: 92,
        name: "Gastly",
        image: "/assets/assets/pokemons/default/92.png",
        type: ["Ghost", "Poison"],
        height: 1.3,
        weight: 0.1,
        baseExperience: 62,
    },
    {
        id: 93,
        name: "Haunter",
        image: "/assets/assets/pokemons/default/93.png",
        type: ["Ghost", "Poison"],
        height: 1.6,
        weight: 0.1,
        baseExperience: 142,
    },
    {
        id: 94,
        name: "Gengar",
        image: "/assets/assets/pokemons/default/94.png",
        type: ["Ghost", "Poison"],
        height: 1.5,
        weight: 40.5,
        baseExperience: 225,
    },
    {
        id: 95,
        name: "Onix",
        image: "/assets/assets/pokemons/default/95.png",
        type: ["Rock", "Ground"],
        height: 8.8,
        weight: 210,
        baseExperience: 77,
    },
    {
        id: 96,
        name: "Drowzee",
        image: "/assets/assets/pokemons/default/96.png",
        type: ["Psychic"],
        height: 1,
        weight: 32.4,
        baseExperience: 66,
    },
    {
        id: 97,
        name: "Hypno",
        image: "/assets/assets/pokemons/default/97.png",
        type: ["Psychic"],
        height: 1.6,
        weight: 75.6,
        baseExperience: 169,
    },
    {
        id: 98,
        name: "Krabby",
        image: "/assets/assets/pokemons/default/98.png",
        type: ["Water"],
        height: 0.4,
        weight: 6.5,
        baseExperience: 65,
    },
    {
        id: 99,
        name: "Kingler",
        image: "/assets/assets/pokemons/default/99.png",
        type: ["Water"],
        height: 1.3,
        weight: 60,
        baseExperience: 166,
    },
    {
        id: 100,
        name: "Voltorb",
        image: "/assets/assets/pokemons/default/100.png",
        type: ["Electric"],
        height: 0.5,
        weight: 10.4,
        baseExperience: 66,
    },
    {
        id: 101,
        name: "Electrode",
        image: "/assets/assets/pokemons/default/101.png",
        type: ["Electric"],
        height: 1.2,
        weight: 66.6,
        baseExperience: 172,
    },
    {
        id: 102,
        name: "Exeggcute",
        image: "/assets/assets/pokemons/default/102.png",
        type: ["Grass", "Psychic"],
        height: 0.4,
        weight: 2.5,
        baseExperience: 65,
    },
    {
        id: 103,
        name: "Exeggutor",
        image: "/assets/assets/pokemons/default/103.png",
        type: ["Grass", "Psychic"],
        height: 2,
        weight: 120,
        baseExperience: 186,
    },
    {
        id: 104,
        name: "Cubone",
        image: "/assets/assets/pokemons/default/104.png",
        type: ["Ground"],
        height: 0.4,
        weight: 6.5,
        baseExperience: 64,
    },
    {
        id: 105,
        name: "Marowak",
        image: "/assets/assets/pokemons/default/105.png",
        type: ["Ground"],
        height: 1,
        weight: 45,
        baseExperience: 149,
    },
    {
        id: 106,
        name: "Hitmonlee",
        image: "/assets/assets/pokemons/default/106.png",
        type: ["Fighting"],
        height: 1.5,
        weight: 49.8,
        baseExperience: 159,
    },
    {
        id: 107,
        name: "Hitmonchan",
        image: "/assets/assets/pokemons/default/107.png",
        type: ["Fighting"],
        height: 1.4,
        weight: 50.2,
        baseExperience: 159,
    },
    {
        id: 108,
        name: "Lickitung",
        image: "/assets/assets/pokemons/default/108.png",
        type: ["Normal"],
        height: 1.2,
        weight: 65.5,
        baseExperience: 77,
    },
    {
        id: 109,
        name: "Koffing",
        image: "/assets/assets/pokemons/default/109.png",
        type: ["Poison"],
        height: 0.6,
        weight: 1,
        baseExperience: 68,
    },
    {
        id: 110,
        name: "Weezing",
        image: "/assets/assets/pokemons/default/110.png",
        type: ["Poison"],
        height: 1.2,
        weight: 9.5,
        baseExperience: 172,
    },
    {
        id: 111,
        name: "Rhyhorn",
        image: "/assets/assets/pokemons/default/111.png",
        type: ["Ground", "Rock"],
        height: 1,
        weight: 115,
        baseExperience: 69,
    },
    {
        id: 112,
        name: "Rhydon",
        image: "/assets/assets/pokemons/default/112.png",
        type: ["Ground", "Rock"],
        height: 1.9,
        weight: 120,
        baseExperience: 170,
    },
    {
        id: 113,
        name: "Chansey",
        image: "/assets/assets/pokemons/default/113.png",
        type: ["Normal"],
        height: 1.1,
        weight: 34.6,
        baseExperience: 395,
    },
    {
        id: 114,
        name: "Tangela",
        image: "/assets/assets/pokemons/default/114.png",
        type: ["Grass"],
        height: 1,
        weight: 35,
        baseExperience: 87,
    },
    {
        id: 115,
        name: "Kangaskhan",
        image: "/assets/assets/pokemons/default/115.png",
        type: ["Normal"],
        height: 2.2,
        weight: 80,
        baseExperience: 172,
    },
    {
        id: 116,
        name: "Horsea",
        image: "/assets/assets/pokemons/default/116.png",
        type: ["Water"],
        height: 0.4,
        weight: 8,
        baseExperience: 59,
    },
    {
        id: 117,
        name: "Seadra",
        image: "/assets/assets/pokemons/default/117.png",
        type: ["Water"],
        height: 1.2,
        weight: 25,
        baseExperience: 154,
    },
    {
        id: 118,
        name: "Goldeen",
        image: "/assets/assets/pokemons/default/118.png",
        type: ["Water"],
        height: 0.6,
        weight: 15,
        baseExperience: 64,
    },
    {
        id: 119,
        name: "Seaking",
        image: "/assets/assets/pokemons/default/119.png",
        type: ["Water"],
        height: 1.3,
        weight: 39,
        baseExperience: 158,
    },
    {
        id: 120,
        name: "Staryu",
        image: "/assets/assets/pokemons/default/120.png",
        type: ["Water"],
        height: 0.8,
        weight: 34.5,
        baseExperience: 68,
    },
    {
        id: 121,
        name: "Starmie",
        image: "/assets/assets/pokemons/default/121.png",
        type: ["Water", "Psychic"],
        height: 1.1,
        weight: 80,
        baseExperience: 182,
    },
    {
        id: 122,
        name: "Mr. Mime",
        image: "/assets/assets/pokemons/default/122.png",
        type: ["Psychic", "Fairy"],
        height: 1.3,
        weight: 54.5,
        baseExperience: 161,
    },
    {
        id: 123,
        name: "Scyther",
        image: "/assets/assets/pokemons/default/123.png",
        type: ["Bug", "Flying"],
        height: 1.5,
        weight: 56,
        baseExperience: 100,
    },
    {
        id: 124,
        name: "Jynx",
        image: "/assets/assets/pokemons/default/124.png",
        type: ["Ice", "Psychic"],
        height: 1.4,
        weight: 40.6,
        baseExperience: 159,
    },
    {
        id: 125,
        name: "Electabuzz",
        image: "/assets/assets/pokemons/default/125.png",
        type: ["Electric"],
        height: 1.1,
        weight: 30,
        baseExperience: 172,
    },
    {
        id: 126,
        name: "Magmar",
        image: "/assets/assets/pokemons/default/126.png",
        type: ["Fire"],
        height: 1.3,
        weight: 44.5,
        baseExperience: 173,
    },
    {
        id: 127,
        name: "Pinsir",
        image: "/assets/assets/pokemons/default/127.png",
        type: ["Bug"],
        height: 1.5,
        weight: 55,
        baseExperience: 175,
    },
    {
        id: 128,
        name: "Tauros",
        image: "/assets/assets/pokemons/default/128.png",
        type: ["Normal"],
        height: 1.4,
        weight: 88.4,
        baseExperience: 172,
    },
    {
        id: 129,
        name: "Magikarp",
        image: "/assets/assets/pokemons/default/129.png",
        type: ["Water"],
        height: 0.9,
        weight: 10,
        baseExperience: 40,
    },
    {
        id: 130,
        name: "Gyarados",
        image: "/assets/assets/pokemons/default/130.png",
        type: ["Water", "Flying"],
        height: 6.5,
        weight: 235,
        baseExperience: 189,
    },
    {
        id: 131,
        name: "Lapras",
        image: "/assets/assets/pokemons/default/131.png",
        type: ["Water", "Ice"],
        height: 2.5,
        weight: 220,
        baseExperience: 219,
    },
    {
        id: 132,
        name: "Ditto",
        image: "/assets/assets/pokemons/default/132.png",
        type: ["Normal"],
        height: 0.3,
        weight: 4,
        baseExperience: 101,
    },
    {
        id: 133,
        name: "Eevee",
        image: "/assets/assets/pokemons/default/133.png",
        type: ["Normal"],
        height: 0.3,
        weight: 6.5,
        baseExperience: 65,
    },
    {
        id: 134,
        name: "Vaporeon",
        image: "/assets/assets/pokemons/default/134.png",
        type: ["Water"],
        height: 1,
        weight: 29,
        baseExperience: 184,
    },
    {
        id: 135,
        name: "Jolteon",
        image: "/assets/assets/pokemons/default/135.png",
        type: ["Electric"],
        height: 0.8,
        weight: 24.5,
        baseExperience: 184,
    },
    {
        id: 136,
        name: "Flareon",
        image: "/assets/assets/pokemons/default/136.png",
        type: ["Fire"],
        height: 0.9,
        weight: 25,
        baseExperience: 184,
    },
    {
        id: 137,
        name: "Porygon",
        image: "/assets/assets/pokemons/default/137.png",
        type: ["Normal"],
        height: 0.8,
        weight: 36.5,
        baseExperience: 79,
    },
    {
        id: 138,
        name: "Omanyte",
        image: "/assets/assets/pokemons/default/138.png",
        type: ["Rock", "Water"],
        height: 0.4,
        weight: 7.5,
        baseExperience: 71,
    },
    {
        id: 139,
        name: "Omastar",
        image: "/assets/assets/pokemons/default/139.png",
        type: ["Rock", "Water"],
        height: 1,
        weight: 35,
        baseExperience: 173,
    },
    {
        id: 140,
        name: "Kabuto",
        image: "/assets/assets/pokemons/default/140.png",
        type: ["Rock", "Water"],
        height: 0.5,
        weight: 11.5,
        baseExperience: 71,
    },
    {
        id: 141,
        name: "Kabutops",
        image: "/assets/assets/pokemons/default/141.png",
        type: ["Rock", "Water"],
        height: 1.3,
        weight: 40.5,
        baseExperience: 173,
    },
    {
        id: 142,
        name: "Aerodactyl",
        image: "/assets/assets/pokemons/default/142.png",
        type: ["Rock", "Flying"],
        height: 1.8,
        weight: 59,
        baseExperience: 180,
    },
    {
        id: 143,
        name: "Snorlax",
        image: "/assets/assets/pokemons/default/143.png",
        type: ["Normal"],
        height: 2.1,
        weight: 460,
        baseExperience: 189,
    },
    {
        id: 144,
        name: "Articuno",
        image: "/assets/assets/pokemons/default/144.png",
        type: ["Ice", "Flying"],
        height: 1.7,
        weight: 55.4,
        baseExperience: 261,
    },
    {
        id: 145,
        name: "Zapdos",
        image: "/assets/assets/pokemons/default/145.png",
        type: ["Electric", "Flying"],
        height: 1.6,
        weight: 52.6,
        baseExperience: 261,
    },
    {
        id: 146,
        name: "Moltres",
        image: "/assets/assets/pokemons/default/146.png",
        type: ["Fire", "Flying"],
        height: 2,
        weight: 60,
        baseExperience: 261,
    },
    {
        id: 147,
        name: "Dratini",
        image: "/assets/assets/pokemons/default/147.png",
        type: ["Dragon"],
        height: 1.8,
        weight: 3.3,
        baseExperience: 60,
    },
    {
        id: 148,
        name: "Dragonair",
        image: "/assets/assets/pokemons/default/148.png",
        type: ["Dragon"],
        height: 4,
        weight: 16.5,
        baseExperience: 147,
    },
    {
        id: 149,
        name: "Dragonite",
        image: "/assets/assets/pokemons/default/149.png",
        type: ["Dragon", "Flying"],
        height: 2.2,
        weight: 210,
        baseExperience: 270,
    },
    {
        id: 150,
        name: "Mewtwo",
        image: "/assets/assets/pokemons/default/150.png",
        type: ["Psychic"],
        height: 2,
        weight: 122,
        baseExperience: 306,
    },

];

export default AllPokemon;
